spring:
  profiles:
    active:
      - development
  datasource:
    url: jdbc:mysql://localhost:3306/pggqlredis?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1590
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 5039
      timeout: 10000ms
  cache:
    type: redis
    redis:
      time-to-live: 30
      cache-null-values: false
  servlet:
    multipart:
      max-file-size: 80MB
  jackson:
    serialization:
      fail-on-empty-beans: false
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      unwrap-root-value: false