spring:
  profiles:
    active:
      - development
  datasource:
    url: jdbc:mysql://localhost:3306/pggqlredis?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1590
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 80MB
